"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

const categories = ["用药治疗", "治疗操作", "交接班", "文书与流程", "其他"];
type Problem = { id:string; title:string; category:string; keywords:string; context:string; solution:string; cautions:string; createdAt:string };
type Form = Omit<Problem,"id"|"createdAt">;
const blank:Form={title:"",category:"",keywords:"",context:"",solution:"",cautions:""};
const demos:Problem[]=[
 {id:"demo-1",title:"夜间出现发热主诉时的信息整理",category:"用药治疗",keywords:"发热, 生命体征, 评估",context:"匿名演示：值班期间收到“患者感觉发热”的转述，需要先补齐关键信息。",solution:"1. 了解主诉出现时间、伴随症状与既往相关情况。\n2. 查看或复测生命体征，结合病情变化按院内流程上报。\n3. 将已完成事项、待完成事项清楚交接。",cautions:"本条仅为匿名学习示例。具体评估和处置以患者实际情况、院内制度及上级医师意见为准。",createdAt:"2026-09-01"},
 {id:"demo-2",title:"临时检验结果回报后的交接记录",category:"用药治疗",keywords:"检验, 危急值, 交接班",context:"匿名演示：收到需要关注的检验回报后，需确保信息传递完整。",solution:"1. 按院内流程核实回报信息。\n2. 记录已联系的对象、联系时间和得到的处理指示。\n3. 在交接班中标注后续观察或复查安排。",cautions:"遵循本机构关于检验结果、危急值与病历记录的要求。",createdAt:"2026-08-30"},
 {id:"demo-3",title:"家属焦虑询问时的沟通准备",category:"用药治疗",keywords:"家属沟通, 告知, 情绪",context:"匿名演示：家属希望立即了解情况，值班人员需在职责范围内进行沟通。",solution:"1. 确认可沟通范围，遵循隐私和授权要求。\n2. 用平实语言说明当前已知事实，不做超出职责范围的承诺。\n3. 说明下一步安排及正式沟通渠道。",cautions:"不得在本工具中记录任何患者或家属身份信息。",createdAt:"2026-08-28"},
 {id:"demo-4",title:"交接班前的待办事项整理",category:"交接班",keywords:"交接班, 待办, 复查",context:"匿名演示：交班前需要整理未完成事项，减少遗漏。",solution:"1. 按轻重缓急列出待完成事项。\n2. 每项写清目前状态、下一步动作和时间点。\n3. 对需重点关注的变化进行口头确认。",cautions:"本工具仅用于经验整理，不替代正式交接文书。",createdAt:"2026-08-25"}
];
const date=(v:string)=>new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"short",day:"numeric"}).format(new Date(v));
const fromRow=(x:any):Problem=>({id:x.id,title:x.title,category:x.category,keywords:x.keywords??"",context:x.context??"",solution:x.solution,cautions:x.cautions??"",createdAt:x.created_at.slice(0,10)});
const rows=(items:Problem[])=>items.map(({createdAt,...x})=>({...x,created_at:`${createdAt}T00:00:00.000Z`}));

export default function Home(){
 const [items,setItems]=useState<Problem[]>([]),[view,setView]=useState<"home"|"list"|"detail"|"new"|"edit">("home"),[selected,setSelected]=useState(""),[query,setQuery]=useState(""),[category,setCategory]=useState("全部分类"),[form,setForm]=useState<Form>(blank),[note,setNote]=useState(""),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);const {data,error}=await supabase.from("problems").select("*").order("created_at",{ascending:false});if(error){setNote("暂时无法连接共享资料库，请稍后刷新。");setLoading(false);return}if(!data?.length){const seeded=await supabase.from("problems").insert(rows(demos)).select();if(seeded.error)setNote("资料库已连接，但演示数据暂未写入。");else{const next=seeded.data.map(fromRow);setItems(next);setSelected(next[0]?.id??"")}}else{const next=data.map(fromRow);setItems(next);setSelected(old=>old||next[0]?.id||"")}setLoading(false)}
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>items.filter(x=>(category==="全部分类"||x.category===category)&&(!query.trim()||`${x.title} ${x.keywords} ${x.solution}`.toLowerCase().includes(query.trim().toLowerCase()))),[items,category,query]);const current=items.find(x=>x.id===selected);
 const detail=(id:string)=>{setSelected(id);setNote("");setView("detail")};const startNew=()=>{setForm(blank);setNote("");setView("new")};const startEdit=()=>{if(!current)return;const {id,createdAt,...editable}=current;setForm(editable);setNote("");setView("edit")};
 async function copy(){if(!current)return;try{await navigator.clipboard.writeText(current.solution);setNote("处理思路已复制，可粘贴到需要的位置。") }catch{setNote("复制未完成，请手动选中文本复制。")}}
 async function submit(e:FormEvent){e.preventDefault();if(view==="edit"&&current){const result=await supabase.from("problems").update(form).eq("id",current.id).select().single();if(result.error){setNote("修改未保存，请稍后再试。");return}setItems(old=>old.map(x=>x.id===current.id?fromRow(result.data):x));setNote("修改已同步到共享资料库。");setView("detail");return}const result=await supabase.from("problems").insert({...form,id:crypto.randomUUID()}).select().single();if(result.error){setNote("保存未完成，请稍后再试。");return}const record=fromRow(result.data);setItems(old=>[record,...old]);setSelected(record.id);setNote("已保存并同步到共享资料库。");setView("detail")}
 const warning=<section className="mb-7 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950"><b>匿名化提醒</b><br/>不得录入患者姓名、住院号、联系方式、身份证号、照片、检查单截图或任何可识别身份的信息。本工具内容对所有使用者开放编辑，仅供学习与工作复盘参考，不替代正式诊疗决策、院内制度或上级医师意见。</section>;
 return <main className="min-h-screen bg-[#f4f7f5] text-slate-900"><header className="border-b border-emerald-950/10 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-4 py-4 sm:px-6"><button onClick={()=>setView("home")} className="text-left"><p className="text-xs font-bold tracking-[.16em] text-emerald-700">值班工作台</p><h1 className="text-lg font-bold">问题与处理方案库</h1></button><button onClick={startNew} className="rounded-xl bg-emerald-800 px-4 py-2.5 text-sm font-semibold text-white">+ 新增问题</button></div></header><div className="mx-auto max-w-6xl px-4 py-7 sm:px-6 sm:py-10">{warning}{note&&<div role="status" className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-900">{note}</div>}{loading?<div className="rounded-2xl bg-white p-8 text-sm text-slate-600">正在读取共享资料库…</div>:<>{view==="home"&&<Dashboard items={items} detail={detail} list={()=>setView("list")} add={startNew}/>} {view==="list"&&<List items={filtered} query={query} category={category} setQuery={setQuery} setCategory={setCategory} detail={detail} add={startNew}/>} {view==="detail"&&current&&<Details item={current} back={()=>setView("list")} copy={copy} edit={startEdit}/>} {(view==="new"||view==="edit")&&<NewForm editing={view==="edit"} form={form} setForm={setForm} submit={submit} cancel={()=>setView(view==="edit"?"detail":"home")} note={note}/>}</>}</div></main>
}
function Dashboard({items,detail,list,add}:{items:Problem[];detail:(id:string)=>void;list:()=>void;add:()=>void}){const recent=[...items].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,4),used=new Set(items.map(x=>x.category)).size;return <><section className="grid gap-6 lg:grid-cols-[1.5fr_1fr]"><div className="rounded-3xl bg-emerald-950 p-7 text-white sm:p-9"><p className="text-sm font-semibold text-emerald-200">个人知识整理 · 云端共享</p><h2 className="mt-3 max-w-xl text-3xl font-bold tracking-tight sm:text-4xl">把值班经验整理成下一次能快速找到的答案。</h2><p className="mt-4 max-w-xl text-sm leading-6 text-emerald-100">内容会同步到共享资料库；更换浏览器或设备后也能看到相同记录。</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={add} className="rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-emerald-950">新增一条问题</button><button onClick={list} className="rounded-xl border border-emerald-300/50 px-4 py-2.5 text-sm font-semibold text-white">查看全部问题</button></div></div><div className="grid grid-cols-2 gap-3"><Stat value={items.length} label="已收录问题"/><Stat value={used} label="使用分类"/><div className="col-span-2 rounded-2xl border border-emerald-100 bg-white p-5"><p className="text-sm font-semibold">开始使用</p><p className="mt-2 text-sm leading-6 text-slate-600">所有使用者均可检索、新增和修改匿名记录，内容会自动同步。</p><button onClick={list} className="mt-4 text-sm font-bold text-emerald-800 underline underline-offset-4">进入检索页</button></div></div></section><section className="mt-9"><div className="mb-4 flex items-end justify-between"><div><p className="text-sm font-bold text-emerald-800">最近新增</p><h2 className="mt-1 text-2xl font-bold">最近收录的问题</h2></div><button onClick={list} className="text-sm font-semibold text-emerald-800">全部记录 →</button></div><div className="grid gap-3 md:grid-cols-2">{recent.map(x=><Card key={x.id} item={x} click={()=>detail(x.id)}/>)}</div></section></>}
function Stat({value,label}:{value:number;label:string}){return <div className="rounded-2xl border border-emerald-100 bg-white p-5"><p className="text-3xl font-bold text-emerald-900">{value}</p><p className="mt-1 text-sm text-slate-600">{label}</p></div>}
function List({items,query,category,setQuery,setCategory,detail,add}:{items:Problem[];query:string;category:string;setQuery:(x:string)=>void;setCategory:(x:string)=>void;detail:(id:string)=>void;add:()=>void}){return <section><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-emerald-800">问题列表</p><h2 className="mt-1 text-3xl font-bold">检索与分类浏览</h2></div><button onClick={add} className="rounded-xl bg-emerald-800 px-4 py-2.5 text-sm font-semibold text-white">+ 新增问题</button></div><div className="mt-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 md:grid-cols-[1fr_220px]"><label className="text-sm font-semibold">关键词搜索<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索标题、关键词或处理思路" className="field"/></label><label className="text-sm font-semibold">问题分类<select value={category} onChange={e=>setCategory(e.target.value)} className="field bg-white"><option>全部分类</option>{categories.map(x=><option key={x}>{x}</option>)}</select></label></div><p className="mt-5 text-sm text-slate-600">找到 {items.length} 条记录</p><div className="mt-3 grid gap-3 md:grid-cols-2">{items.length?items.map(x=><Card key={x.id} item={x} click={()=>detail(x.id)}/>):<div className="col-span-full rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><b>没有找到相符的问题</b><p className="mt-2 text-sm text-slate-600">尝试更换关键词或清除分类筛选。</p></div>}</div></section>}
function Card({item,click}:{item:Problem;click:()=>void}){return <button onClick={click} className="rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-emerald-300 hover:shadow-md"><div className="flex items-start justify-between gap-3"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-800">{item.category}</span><span className="shrink-0 text-xs text-slate-500">{date(item.createdAt)}</span></div><h3 className="mt-4 text-lg font-bold">{item.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-600">{item.context}</p><p className="mt-4 text-xs font-semibold text-emerald-800">{item.keywords}</p></button>}
function Details({item,back,copy,edit}:{item:Problem;back:()=>void;copy:()=>void;edit:()=>void}){return <article className="mx-auto max-w-3xl"><button onClick={back} className="text-sm font-semibold text-emerald-800">← 返回问题列表</button><div className="mt-5 rounded-3xl border border-slate-200 bg-white p-6 sm:p-9"><div className="flex flex-wrap items-center gap-3"><span className="rounded-full bg-emerald-50 px-3 py-1 text-sm font-bold text-emerald-800">{item.category}</span><span className="text-sm text-slate-500">收录于 {date(item.createdAt)}</span><button onClick={edit} className="ml-auto rounded-lg border border-slate-300 px-3 py-2 text-sm font-bold text-slate-700">编辑问题</button></div><h2 className="mt-5 text-3xl font-bold">{item.title}</h2><p className="mt-3 text-sm font-medium text-slate-600">关键词：{item.keywords||"未填写"}</p><Block title="遇到的场景或背景" text={item.context}/><div className="mt-7 rounded-2xl border border-emerald-100 bg-emerald-50 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-bold text-emerald-950">处理思路或步骤</h3><button onClick={copy} className="rounded-lg border border-emerald-300 bg-white px-3 py-2 text-sm font-bold text-emerald-900">复制处理思路</button></div><p className="mt-4 whitespace-pre-line text-sm leading-7 text-slate-800">{item.solution}</p></div><Block title="注意事项" text={item.cautions||"未填写"}/></div></article>}
function Block({title,text}:{title:string;text:string}){return <section className="mt-7"><h3 className="font-bold">{title}</h3><p className="mt-3 whitespace-pre-line text-sm leading-7 text-slate-700">{text}</p></section>}
function NewForm({editing,form,setForm,submit,cancel,note}:{editing:boolean;form:Form;setForm:(x:Form)=>void;submit:(e:FormEvent)=>void;cancel:()=>void;note:string}){const set=(k:keyof Form,v:string)=>setForm({...form,[k]:v});return <section className="mx-auto max-w-3xl"><button onClick={cancel} className="text-sm font-semibold text-emerald-800">← 返回{editing?"问题详情":"首页"}</button><div className="mt-5 rounded-3xl border border-slate-200 bg-white p-6 sm:p-9"><p className="text-sm font-bold text-emerald-800">{editing?"修改问题":"新增问题"}</p><h2 className="mt-1 text-3xl font-bold">{editing?"更新这条匿名经验":"记录一条匿名经验"}</h2><p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm leading-6 text-amber-950">请勿填写患者姓名、住院号、联系方式、具体身份特征或任何可识别患者的信息。</p><form onSubmit={submit} className="mt-6 grid gap-5"><label className="text-sm font-bold">问题标题 <i className="text-rose-600">*</i><input required value={form.title} onChange={e=>set("title",e.target.value)} placeholder="例如：夜间发热主诉的信息整理" className="field"/></label><label className="text-sm font-bold">问题分类 <i className="text-rose-600">*</i><select required value={form.category} onChange={e=>set("category",e.target.value)} className="field bg-white"><option value="">请选择分类</option>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-bold">关键词<input value={form.keywords} onChange={e=>set("keywords",e.target.value)} placeholder="用逗号分隔，例如：发热, 生命体征" className="field"/></label><label className="text-sm font-bold">遇到的场景或背景<textarea value={form.context} onChange={e=>set("context",e.target.value)} placeholder="只描述去标识化的场景，不要填写任何个人信息。" className="field min-h-28"/></label><label className="text-sm font-bold">处理思路或步骤 <i className="text-rose-600">*</i><textarea required value={form.solution} onChange={e=>set("solution",e.target.value)} placeholder="按步骤写下处理思路。" className="field min-h-36"/></label><label className="text-sm font-bold">注意事项<textarea value={form.cautions} onChange={e=>set("cautions",e.target.value)} placeholder="例如：需遵循院内流程、及时上报等。" className="field min-h-24"/></label>{note&&<p className="text-sm font-semibold text-rose-700">{note}</p>}<div className="flex flex-wrap gap-3"><button type="submit" className="rounded-xl bg-emerald-800 px-5 py-3 text-sm font-bold text-white">{editing?"保存修改":"保存问题"}</button><button type="button" onClick={cancel} className="rounded-xl border border-slate-300 px-5 py-3 text-sm font-semibold">取消</button></div></form></div></section>}

